// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package user

import (
	"database/sql"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/os/gtime"
)

// Entity is the golang structure for table user.
type Entity struct {
    Id         int         `orm:"id,primary"  json:"id"`          // 主键      
    Passport   string      `orm:"passport"    json:"passport"`    // 用户账号  
    Password   string      `orm:"password"    json:"password"`    // 用户密码  
    Nickname   string      `orm:"nickname"    json:"nickname"`    // 用户昵称  
    Email      string      `orm:"email"       json:"email"`       // 邮箱      
    Sex        int         `orm:"sex"         json:"sex"`         // 用户类型  
    Signature  string      `orm:"signature"   json:"signature"`   //           
    Status     int         `orm:"status"      json:"status"`      // 账号状态  
    Avatar     string      `orm:"avatar"      json:"avatar"`      //           
    CreateTime *gtime.Time `orm:"create_time" json:"create_time"` // 创建时间  
    UpdateTime *gtime.Time `orm:"update_time" json:"update_time"` // 更新时间  
    DeleteTime *gtime.Time `orm:"delete_time" json:"delete_time"` // 删号时间  
}

// OmitEmpty sets OPTION_OMITEMPTY option for the model, which automatically filers
// the data and where attributes for empty values.
func (r *Entity) OmitEmpty() *arModel {
	return Model.Data(r).OmitEmpty()
}

// Inserts does "INSERT...INTO..." statement for inserting current object into table.
func (r *Entity) Insert() (result sql.Result, err error) {
	return Model.Data(r).Insert()
}

// InsertIgnore does "INSERT IGNORE INTO ..." statement for inserting current object into table.
func (r *Entity) InsertIgnore() (result sql.Result, err error) {
	return Model.Data(r).InsertIgnore()
}

// Replace does "REPLACE...INTO..." statement for inserting current object into table.
// If there's already another same record in the table (it checks using primary key or unique index),
// it deletes it and insert this one.
func (r *Entity) Replace() (result sql.Result, err error) {
	return Model.Data(r).Replace()
}

// Save does "INSERT...INTO..." statement for inserting/updating current object into table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
func (r *Entity) Save() (result sql.Result, err error) {
	return Model.Data(r).Save()
}

// Update does "UPDATE...WHERE..." statement for updating current object from table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
func (r *Entity) Update() (result sql.Result, err error) {
	return Model.Data(r).Where(gdb.GetWhereConditionOfStruct(r)).Update()
}

// Delete does "DELETE FROM...WHERE..." statement for deleting current object from table.
func (r *Entity) Delete() (result sql.Result, err error) {
	return Model.Where(gdb.GetWhereConditionOfStruct(r)).Delete()
}